stages:
  - build
  - post-build
  - deploy
  - rollback

cache:
  untracked: true
  key: "$CI_PROJECT_ID"
  paths:
    - node_modules/
    - _site/vendor/
    - .bundled/
    - .yarn

build:
  stage: build
  image: node:8-alpine
  before_script:
    - yarn install --pure-lockfile --cache-folder .yarn
  script:
    - yarn build
  artifacts:
    paths:
      - dist/

docker-build:
  stage: post-build
  image: docker:stable
  dependencies:
    - build
  services:
    - docker:dind
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
  variables:
    DOCKER_DRIVER: overlay2
    CONTAINER_IMAGE: registry.gitlab.com/$CI_PROJECT_PATH
  script:
    - yarn install --pure-lockfile --cache-folder .yarn --production
    - docker build --pull -t $CONTAINER_IMAGE:$CI_COMMIT_SHA -t $CONTAINER_IMAGE:latest .
    - docker push $CONTAINER_IMAGE:$CI_COMMIT_SHA
    - docker push $CONTAINER_IMAGE:latest

sentry:
  stage: post-build
  image: 
    name: getsentry/sentry-cli
    entrypoint: ["/bin/sh"]
  dependencies:
    - build
  script:
    - sentry-cli releases new "$CI_COMMIT_SHA"
    - sentry-cli releases set-commits "$CI_COMMIT_SHA" --auto
    - sentry-cli releases files "$CI_COMMIT_SHA" upload-sourcemaps ./dist
    - sentry-cli releases finalize "$CI_COMMIT_SHA"

deploy:
  stage: deploy
  image: ubuntu:18.04
  variables:
    CONTAINER_IMAGE: registry.gitlab.com/$CI_PROJECT_PATH
  environment:
    name: production
    url: https://tribesrevengeance.net
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - curl -sL https://sentry.io/get-cli/ | bash
  script:
    - ssh -o StrictHostKeyChecking=no $DEPLOY_HOST "docker pull $CONTAINER_IMAGE:$CI_COMMIT_SHA"
    - ssh -o StrictHostKeyChecking=no $DEPLOY_HOST "docker service update --image $CONTAINER_IMAGE:$CI_COMMIT_SHA --env-add SENTRY_RELEASE:$CI_COMMIT_SHA $DEPLOY_SERVICE || (docker service rollback $DEPLOY_SERVICE && exit 1)"
    - sentry-cli releases deploys "$CI_COMMIT_SHA" new -e production
