stages:
  - build
  - deploy

build:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
  variables:
    DOCKER_DRIVER: overlay2
    CONTAINER_IMAGE: registry.gitlab.com/$CI_PROJECT_PATH
  script:
    - docker pull $CONTAINER_IMAGE:latest || true
    - docker build --pull -t $CONTAINER_IMAGE:latest .
    - docker push $CONTAINER_IMAGE:latest

deploy:
  stage: deploy
  image: ubuntu:18.04
  variables:
    CONTAINER_IMAGE: registry.gitlab.com/$CI_PROJECT_PATH
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - ssh -o StrictHostKeyChecking=no $DEPLOY_HOST "docker pull $CONTAINER_IMAGE:latest && docker service update --image $CONTAINER_IMAGE:latest $DEPLOY_SERVICE"
